name: nullpass
description: NullPass is a locally managed password manager
publish_to: none

version: 0.0.1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_scan2: ^4.2.1
  cached_network_image: ^3.2.0
  flutter_app_lock: ^2.0.0
  flutter_secure_storage: ^5.0.2
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.1.0
  local_auth: ^1.1.8
  material_design_icons_flutter: ^5.0.6595
  onesignal_flutter: ^2.6.2
  openpgp: ^3.1.0
  otp: ^3.0.2
  path_provider: ^2.0.7
  qr_flutter: ^4.0.0
  secure_screen_switcher:
    git:
      url: git@github.com:pseudorand-dev/secure_screen_switcher.git
      ref: main
  shared_preferences: ^2.0.9
  sqflite: ^2.0.0
  timeline_list: ^0.0.6
  url_launcher: ^6.0.17
  uuid: ^3.0.5
  validators: ^3.0.0
  vibration: ^1.7.2
  visibility_detector: ^0.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/null_iosScaledDown_1500_Transparent.png"
  image_path_android: "assets/images/null_iosScaledDown_1500_Transparent.png"


flutter:
  assets:
    - assets/images/
  uses-material-design: true
