name: nullpass
description: NullPass is a locally managed password manager

version: 0.0.1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.1.0+1
  flutter_secure_storage: ^3.3.1+1
  flutter_widgets: ^0.1.7+1
  font_awesome_flutter: ^8.5.0
  path_provider: ^1.3.0
  shared_preferences: 0.5.3+4
  sqflite: ^1.1.7
  url_launcher: ^5.1.6
  uuid: ^2.0.1
  validators: ^2.0.0+1
  vibration: 1.2.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/null_iosScaledDown_1500_Transparent.png"
  image_path_android: "assets/images/null_iosScaledDown_1500_Transparent.png"

# Flutter specific
flutter:

  uses-material-design: true

  # assets
  assets:
    - assets/images/

